### ISSUE TITLE
Dank null crashes client

### ISSUE THREAD

**Issue by wideblaze** [wideblaze/DigSite#24]
Several reports of dank null crashing .23 update

Work around: remove dank null mod. It is not required

**Comment by KokSaker** [comment]
Can confirm. Neither me from windows 10 cliend nor my friend from his macbook couldn't connect to the server. Server runs but it doesn't accept us, the client(not the server) crashes when we try to log in.
Edit: Removing the dank null mod from the client just simply doesn't accpet the login with a message that the server couldn't find the mod on a client. So the dank null is actually required to connect to the server it seems. May I suggest removing the mod completely since it has a history and there is actually a better alternative - dank storage.

**Comment by wideblaze** [comment]
Removed dank null in version 1.0.25
