### ISSUE TITLE
flux network

### ISSUE THREAD

**Issue by infamouscake2** [wideblaze/DigSite#43]
Im currently in the sparrow trying charge my jetpack and trying to figure out why my flux network isnt working, everything is outputting power exept my flux point. Ive been looking all over youtube and the internet to see if anyone has had the same issues as me but havent been able to find anything. Can I get some help if possible?

**Comment by wideblaze** [comment]
So I'm not sure what your exact issue is but there are some common things that can happen:

Network:
* ensure you have placed the flux controller and ADDED your own flux network. This can be a little tricky if you have not done this before. 
* ensure all flux components are connected to that network
* If you have already done this, try removing all networks and create a new one. 

Power Source:
* Ensure you have the flux PLUG connected to a power source and the flux POINT is connected to a machine needing power. It's important that the right ones are connected to the right things.
* Ensure power is not being fully consumed by some other connected machine.

Unloaded chunk:
* Ensure your flux network components are located in loaded chunkes. Use FTB util chunk loading or chunk loader if this is potential root cause. I don't trust the flux network chunk loading option on the flux devices.

Trouble powering the sparrow station factory:
* This is the puzzle to be solved for this station. I have posted a spoiler for those truly stuck.
https://github.com/wideblaze/DigSite/wiki/SPOILERS 

Please let me know if any of these solves your issue or provide more details if it doesn't.

**Comment by infamouscake2** [comment]
I had everyhing connected to the same network at first and tired making a new one and connected them all to it again, that didnt work. then i tried putting down a chunk loarder in the sparrow and that didnt seem to work either. I have only connected the flux point to one machine because I only have one flux point on the network. Maybe Pictures might help? Im realizing that jetpacks arent neccesarry to play at the moment and maybe I should just continue with the quests but It would be nice to fly around with them and not destroy my elytra.
![Screenshot (16)](https://user-images.githubusercontent.com/63136805/78454289-09aac500-764c-11ea-8a23-7b49f74bb051.png) 
![Screenshot (17)](https://user-images.githubusercontent.com/63136805/78454298-129b9680-764c-11ea-9587-a83c4b67de31.png)
![Screenshot (18)](https://user-images.githubusercontent.com/63136805/78454302-192a0e00-764c-11ea-9940-84650b3eab83.png)
![Screenshot (19)](https://user-images.githubusercontent.com/63136805/78454313-247d3980-764c-11ea-89af-f991e49ead63.png)
![Screenshot (20)](https://user-images.githubusercontent.com/63136805/78454316-2a731a80-764c-11ea-8b3c-5cf379ecd652.png)
![Screenshot (21)](https://user-images.githubusercontent.com/63136805/78454318-2f37ce80-764c-11ea-9128-fbd5ff47ba17.png)

thanks for responding so quickly I honestly thought this may take days, but you made it very quick. thank you

**Comment by wideblaze** [comment]
You will need the point to be in working order to progress the questline

OK a couple of things I can see in the pics
1) you have a valid network
2) power has flowed across this network in the past
3) your basic storage is full of power now
4) the mekanism power cables appear powered (green light) or have been powered in the past

I don't any connected machines but assume they are to the right on your first pic

OK so if nothing is pulling power and your storage is full (as it is) power will not flow across network. That is expected behavior. 

But if you do have connected machines and they are not receiving power.... hmmmmm

1) check that you do not have 2 networks with the same name (this is a easy thing to accidentally do)

2) test with a different machine (break the cable at the ranch powering the deep learning machines and and connect point there, see if they will pull power)

3) check the connected machine is not already full of power. Maybe you need to dump (vent) the oxygen side if it's 100% full to cause it to continue filling hydrogen side.

**Comment by wideblaze** [comment]
assume resolved, re-open if needed
