### ISSUE TITLE
Server start problem

### ISSUE THREAD

**Issue by Skylife27** [wideblaze/DigSite#46]
Originally under settings.cfg it says
FORGEURL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2- **14.23.5.2854** -installer.jar

And it failed so i found a way to get around this but i dont know if it's a total fix
FORGEURL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2- **14.23.5.2847** -installer.jar

**Comment by wideblaze** [comment]
I will look into, I did not test server install script after updating it to 14.23.5.2854

**Comment by SyntheticSponge** [comment]
I've got an addition to this as well, when the script finishes installing the forge file, the start script continues to loop install due to a if statement checking for forge-universal instead of the installed forge jar. 

Line 471~
{REM Check if forge is already installed
IF NOT EXIST "%~dp0*forge*%MC_SERVER_FORGEVER%*universal*.jar"}.

**Comment by wideblaze** [comment]
BUG, will be fixed in next release
Workaround:

modify settings.cfg

lines 26-27
TO:

`FORGEVER=14.23.5.2854
FORGEURL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar
`

**Comment by wideblaze** [comment]
issue fixed in 1.0.29 https://www.curseforge.com/minecraft/modpacks/digsite/files/2961677
